apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgp-kubeserve
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pgp-kubeserve
  template:
    metadata:
      labels:
        app: pgp-kubeserve
    spec:
      containers:
       - name: app
         image: nikhildeopujari2007/pgp-kubedockerimage:4
         ports:
           - containerPort: 8080
         env:
           - name: PORT
             value: "8080"
---
kind: Service
apiVersion: v1
metadata:
   name: pgp-kubeserve-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector: 
    app: pgp-kubeserve
